spring.application.name=ChatBot

openapi.server.url = https://api.openai.com/v1/chat/completions
openapi.api.key = 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
openapi.api.model= gpt-4o-mini
