spring.application.name=ChatBot

openapi.server.url=https://api.openai.com/v1/chat/completions
openapi.api.key=YDevPT31ijxJX52defo9rWM4oxexhogKXKVLGPzThMt6cn_g1ML_Ma4GmN7QDi_TP6GT3BlbkFJnxUIhxPioEWolfCIdcHtd_SSWrm0z0b9nRtNFlvPw_A9wCAW7ZrEBV4HTirxAXHygpLJ2h2VEA
openapi.api.model=gpt-4o-mini
